obj-$(CONFIG_NET_DSA_SJA1105) += sja1105.o

sja1105-objs := \
    sja1105-spi.o \
    sja1105-main.o \
    sja1105-ethtool.o \
    sja1105-clocking.o \
    sja1105-static-config.o \
    sja1105-dynamic-config.o \

